# NIVELL 1
Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques..



## - Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. .


In [16]:
import numpy as np
unaDimensio = np.array([3,8,95,4,8,78,2,15,6,98,2,36,54,78,95,25,29,32,30,22], dtype='int64')
print(unaDimensio)

print("La dimensió de la matriu és de", unaDimensio.ndim)

print("La forma de la matriu és de", unaDimensio.shape)

[ 3  8 95  4  8 78  2 15  6 98  2 36 54 78 95 25 29 32 30 22]
La dimensió de la matriu és de 1
La forma de la matriu és de (20,)


## - Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.


In [34]:
print("La mitjana de la matriu és", np.mean(unaDimensio))

print("Si restem la mitjana anterior a cadascún dels valors, la matriu queda així", unaDimensio - np.mean(unaDimensio))

La mitjana de la matriu és 36.0
Si restem la mitjana anterior a cadascún dels valors, la matriu queda així [-33. -28.  59. -32. -28.  42. -34. -21. -30.  62. -34.   0.  18.  42.
  59. -11.  -7.  -4.  -6. -14.]


## - Exercici 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [42]:
duesDimensions = np.random.randint(100, size=(2,5))
print(duesDimensions)

print("El valor màxim de la matriu és el", np.max(duesDimensions))

print("Els valors màxims de l'eix 0 són", np.max(duesDimensions, axis=0), " i els de l'eix 1 són els", np.max(duesDimensions, axis=1))


[[49 77 98 93 60]
 [ 6  8 34 70 34]]
El valor màxim de la matriu és el 98
Els valors màxims de l'eix 0 són [49 77 98 93 60]  i els de l'eix 1 són els [98 70]


# NIVELL 2
Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask..



## - Exercici 4
Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".



In [19]:
#Exemple 1: suma de matrius de tamany igual
matriuA = np.random.randint(10, size=(2,3))
matriuB = np.random.randint(5, size=(2,3))
print(matriuA)
print("____________________________")
print(matriuB)
print("____________________________")
novaMatriu = np.add(matriuA, matriuB)
print(novaMatriu)

[[7 2 0]
 [4 8 9]]
____________________________
[[3 2 1]
 [4 4 3]]
____________________________
[[10  4  1]
 [ 8 12 12]]


In [21]:
#Exemple 2: suma de matrius amb una de tamany amb mida 1
matriuA = np.random.randint(10, size=(2,3,4))
matriuB = np.random.randint(5, size=(2,1,1))
print(matriuA)
print("____________________________")
print(matriuB)
novaMatriu = np.add(matriuA, matriuB)
print("____________________________")
print(novaMatriu)

[[[5 6 2 7]
  [8 6 1 8]
  [6 2 1 3]]

 [[2 1 6 5]
  [0 1 9 6]
  [8 1 2 9]]]
____________________________
[[[1]]

 [[3]]]
____________________________
[[[ 6  7  3  8]
  [ 9  7  2  9]
  [ 7  3  2  4]]

 [[ 5  4  9  8]
  [ 3  4 12  9]
  [11  4  5 12]]]


## - Exercici 5
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.



In [40]:
matriuA = np.random.randint(10, size=(4,6))
matriuB = np.random.randint(10, size=(1,6))
print(matriuA)
print("____________________________")
print(matriuB)

novaMatriu = np.add(matriuA, matriuB)
print("____________________________")
print(novaMatriu)

#Extracció dels valors d'una columna
print("Els valors de la primera columna de la novaMatriu són", novaMatriu[0:5, 0])

#Suma dels valors d'una columna
sumaC = np.sum(novaMatriu[0:5,0])
print("La suma dels valors de la primera columna de la novaMatriu és de", sumaC)

#Extracció dels valors d'una fila
print("Els valors de la tercera fila de la novaMatriu són", novaMatriu[2:3])

#Suma dels valors d'una fila
sumaF = np.sum(novaMatriu[2:3])
print("La suma dels valors de la tercera fila de la novaMatriu és de", sumaF)

#Suma dels valors d'una columna i una fila
print("La suma dels valors de la primera columna i de la tercera fila de la novaMatriu és de", sumaC+sumaF)

[[0 2 9 1 7 7]
 [3 9 9 9 0 6]
 [6 6 5 6 3 1]
 [1 9 7 3 2 6]]
____________________________
[[4 2 3 0 2 4]]
____________________________
[[ 4  4 12  1  9 11]
 [ 7 11 12  9  2 10]
 [10  8  8  6  5  5]
 [ 5 11 10  3  4 10]]
Els valors de la primera columna de la novaMatriu són [ 4  7 10  5]
La suma dels valors de la primera columna de la novaMatriu és de 26
Els valors de la tercera fila de la novaMatriu són [[10  8  8  6  5  5]]
La suma dels valors de la tercera fila de la novaMatriu és de 42
La suma dels valors de la primera columna i de la tercera fila de la novaMatriu és de 68


## - Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.



In [46]:
print(novaMatriu)
mask = novaMatriu%4 ==0      #si el número dividit pel mòdul de 4 és 0, el número és divisible per 4, per tant, true
print(mask)



[[ 4  4 12  1  9 11]
 [ 7 11 12  9  2 10]
 [10  8  8  6  5  5]
 [ 5 11 10  3  4 10]]
[[ True  True  True False False False]
 [False False  True False False False]
 [False  True  True False False False]
 [False False False False  True False]]


## - Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

# Nivell 3
Manipulació d’imatges amb Matplotlib.

Carregareu qualsevol imatge (jpg, png ..) amb Matplotlib. adoneu-vos que les imatges RGB (Red, Green, Blue) són realment només amplades × alçades × 3 matrius (tres canals Vermell, Verd i Blau), una per cada color de nombres enters int8,

manipuleu aquests bytes i torneu a utilitzar Matplotlib per desar la imatge modificada un cop hàgiu acabat.

Ajuda:Importeu, import matplotlib.image as mpimg. estudieu el metodde mpimg.imread(()



## - Exercici 8
Mostreu-me a veure que passa quan eliminem el canal G Verd o B Blau.

Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.

Utilitzar el mètode, mpimg.imsave () de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.

Objectius
dimensions, formes
Vectoritzacio, Broadcasting
Index i mask
Manipulació imatges amb numpy
